- hosts: web1
  tasks:
  - name: create a folder and file , copy the content
    file: 
      path: "/web1"
      state: directory
  
  - copy:
     src: "web.html"
     dest: "/web1"

  - command: pip3 install docker 
    name: install python
  
  - name: docker_login_registry
    docker_login:
      username: srronak
      password: SRronak@11
  
  - name: docker image
    docker_image: 
          name: srronak/ronak
          source: pull

  - name: create a container
    docker_container:
      name: web_container
      image: srronak/ronak
      state: started
      ports:
       - "8081:80"
      exposed_ports:
       - 80
      volumes:
       - /web1/:/var/www/html
    register: x
  - debug:
      var: x

